### ISSUE TITLE
Act.1; Mapa mental de Investigación Documental, Emmanuel Marx Salazar González 1BS

### ISSUE THREAD

**Issue by marxgonzalez29** [SistemasTecTlaxiaco/actividad-1-mapa-mental-marxgonzalez29#1]
![IMG_20220903_193836](https://user-images.githubusercontent.com/112300981/188292758-dd8dfb67-b24f-4477-b32a-0744008c3eae.jpg)

**Comment by Jaczibeth** [comment]
de 20% sacaste el 18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
